import type { Metadata, Viewport } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { SITE_URL, company } from "@/lib/site-config";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default:
      "Globixs Technology Solutions | AI Automation · Digital Marketing · Technology Consulting",
    template: "%s | Globixs Technology Solutions",
  },
  description:
    "Globixs Technology Solutions — AI automation, digital marketing and technology consulting. Seattle-based, working nationwide.",
  keywords: [
    "AI automation services",
    "AI receptionist",
    "business process automation",
    "digital marketing Seattle",
    "technology consulting Seattle",
    "POS integration",
    "business intelligence dashboards",
    "IT staffing Seattle",
    "job marketing service",
  ],
  authors: [{ name: "Globixs Technology Solutions" }],
  creator: "Globixs Technology Solutions",
  publisher: "Globixs Technology Solutions",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Globixs Technology Solutions",
    title:
      "Globixs Technology Solutions | AI Automation · Digital Marketing · Technology Consulting",
    description:
      "Globixs Technology Solutions — AI automation, digital marketing and technology consulting. Seattle-based, working nationwide.",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Globixs Technology Solutions — AI Automation, Digital Marketing, Technology Consulting",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title:
      "Globixs Technology Solutions | AI Automation · Digital Marketing · Technology Consulting",
    description:
      "Globixs Technology Solutions — AI automation, digital marketing and technology consulting. Seattle-based, working nationwide.",
    images: ["/og-image.png"],
  },
  // Icons come from the App Router file conventions (src/app/favicon.ico,
  // icon.png, apple-icon.png) and the manifest from src/app/manifest.ts —
  // all generated by `npm run favicons:generate`.
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
    },
  },
};

// Next.js emits <meta name="theme-color"> from the viewport export (not from
// metadata) — brand red so the browser chrome matches the mark.
export const viewport: Viewport = {
  themeColor: "#C8262C",
};

/**
 * Organization structured data. Rendered once in the root layout so every
 * page carries it; sameAs links the LinkedIn company page to the site.
 */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: company.name,
  url: SITE_URL,
  logo: `${SITE_URL}/icon-512.png`,
  email: company.email,
  telephone: company.phone,
  address: {
    "@type": "PostalAddress",
    addressLocality: "Seattle",
    addressRegion: "WA",
    addressCountry: "US",
  },
  sameAs: [company.linkedinUrl],
} as const;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <script
          type="application/ld+json"
          // JSON-LD is a static, server-rendered object — no user input.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        {children}
      </body>
    </html>
  );
}
