import type { MetadataRoute } from "next";

// Served at /manifest.webmanifest and linked from <head> automatically by
// the App Router file convention. Icons are generated by
// `npm run favicons:generate` (scripts/generate-favicons.ts).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Globixs Technology Solutions",
    short_name: "Globixs",
    description:
      "AI automation, digital marketing and technology consulting. Seattle-based, working nationwide.",
    start_url: "/",
    display: "standalone",
    theme_color: "#C8262C",
    background_color: "#1F2326",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
      { src: "/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
